# Конфигурация SpawnChestPlugin v2.0
# Эпичные сундуки с лутом и охранниками!

settings:
  # Интервал спавна сундуков в секундах (по умолчанию 30 минут)
  spawn-interval-seconds: 14400
  
  # Зона спавна (от центра мира)
  spawn-zone:
    min-distance: 400    # Минимальное расстояние от центра
    max-distance: 2000   # Максимальное расстояние от центра
    min-height: 60       # Минимальная высота спавна
    max-height: 200      # Максимальная высота спавна
  
  # Шансы на разные типы сундуков (должно в сумме давать 1.0)
  chest-chances:
    common: 0.70     # 70% - обычные сундуки
    rare: 0.25       # 25% - редкие сундуки  
    legendary: 0.05  # 5% - легендарные сундуки
  
  # Настройки охранников
  guardians:
    enabled: true
    common-count: 1      # Количество охранников у обычного сундука
    rare-count: 2        # Количество охранников у редкого сундука
    legendary-count: 3   # Количество охранников у легендарного сундука
  
  # Эффекты
  effects:
    particles: true      # Включить эффекты частиц
    lightning: true      # Молния для легендарных сундуков
    sounds: true         # Звуковые эффекты

messages:
  # Основные сообщения
  spawn-title: "§6✨ Сундук появился! ✨"
  spawn-subtitle: "§eКоординаты: §fX: %x% Y: %y% Z: %z%"
  
  # Сообщения о спавне
  chest-spawned: "§6🎁 %tier% §aпоявился по координатам: §e%coords%"
  chest-now: "§a✅ Сундук был создан немедленно!"
  
  # Предупреждения
  minutes-left: "§e⏰ %minutes% минут до появления следующего сундука!"
  seconds-left: "§e⏰ %seconds% секунд до появления сундука!"
  countdown: "§c⚡ %seconds% секунд до появления сундука!"
  
  # Команды
  next-chest: "§6⏰ До следующего сундука: §e%minutes% мин. %seconds% сек."
  
  # Ошибки
  no-permission: "§c❌ У вас нет прав на использование этой команды!"
  invalid-number: "§c❌ Введите корректное число!"
  world-not-found: "§c❌ Мир не найден!"
  
  # Помощь
  help-header: "§6=== SpawnChest Команды ==="
  help-nextchest: "§e/nextchest §7- Показать время до следующего сундука"
  help-spawn: "§e/spawnchestnow §7- Создать сундук немедленно"
  help-timer: "§e/setchesttimer <секунды> §7- Изменить интервал"
  help-reload: "§e/reloadchestconfig §7- Перезагрузить конфиг"
  help-stats: "§e/cheststats §7- Показать статистику сундуков"