name: SpawnChestPlugin
version: 4.1.5
main: com.myplugin.SpawnChestPlugin
api-version: '1.18'
description: Treasure chest events with legendary items, guardians, achievements. Supports 1.18-1.21+
author: Bohdan Stepantsov

commands:
  chestnow:
    description: Spawn a chest immediately
    permission: spawnchest.admin
    aliases: [spawnchestnow]
  nextchest:
    description: Show time until next chest
    permission: spawnchest.use
    aliases: [nc]
  setchesttimer:
    description: Set the chest spawn interval
    permission: spawnchest.admin
  chestconfig:
    description: View or modify configuration
    permission: spawnchest.admin
    aliases: [cc]
  togglelegendary:
    description: Toggle legendary items on/off
    permission: spawnchest.admin
  togglefeature:
    description: Toggle features on/off
    permission: spawnchest.admin
  reloadchestconfig:
    description: Reload the configuration and language
    permission: spawnchest.admin
  cheststats:
    description: View chest statistics
    permission: spawnchest.admin
  cooldowns:
    description: View your legendary item cooldowns
    permission: spawnchest.use
    aliases: [cd]
  getlegendaryitems:
    description: Get all legendary items
    permission: spawnchest.admin
    aliases: [getlegendary, gli]
  testchestzone:
    description: Test chest spawn zone
    permission: spawnchest.admin
  giveapple:
    description: Give a Summoner Apple
    permission: spawnchest.admin
  mystats:
    description: View your statistics
    permission: spawnchest.use
    aliases: [stats]
  leaderboard:
    description: View the leaderboard
    permission: spawnchest.use
    aliases: [lb, top]
  putintothechest:
    description: Open custom loot editor GUI
    permission: spawnchest.admin
    aliases: [customloot, chestloot, editloot]

permissions:
  spawnchest.use:
    description: Basic permissions
    default: true
  spawnchest.admin:
    description: Admin permissions
    default: op
  spawnchest.legendary:
    description: Can receive legendary items
    default: true
  spawnchest.apple:
    description: Can use Summoner Apple
    default: true
  spawnchest.bypass:
    description: Bypass cooldowns
    default: op